[package]
name = "aes-gcm-siv-wasm"
version = "0.1.0"
description = "A WASM library to encrypt/decrypt text using AES-GCM-SIV"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
aes-gcm-siv = { git = "https://github.com/Verified-Bot/AEADs" }
base64 = "0.20.0"