name: NPM Deploy Package

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'latest'

    - name: Fetch token from Github Secrets and run Deploy Script
      run: ./build.sh

    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'
        - run: npm publish ./pkg
          env:
              NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}



